package com.epam.streamdp.four.enums;

public enum AcademicSubjects {
    MATHS, PSYCHOLOGY, ELECTRICAL_ENGINEERING, COMPUTER_SCIENCE, ENGLISH, THERMODYNAMICS, HYDRODYMAMICS,
    BOILER_PLANTS, STRENGHT_OF_MATERIALS, MECHANICS, COMBUSTION_THEORY, PUMPING_UNITS, TFOEE, ISB,
    ELECTRONIC_DEVICES, ECONOMY
}
