package com.epam.streamdp.three.enums;

public enum MineralColors {
    BLUE, BLUE_PALE, BLUE_DEEP, BLUE_GREENISH,BLUISH_GREEN_DEEP, BLUISH_GREEN, BLUE_LIGHT, BLUE_ROYAL, BLUE_SKY, BLUE_CERULEAN, BLUE_GREEN,
    RED, RED_CHERRY, RED_ROSE, RED_PINK, RED_PURPLE, RED_BROWN, RED_DEEP, RED_ORANGE, REDDISH_BROWN,
    GREEN, GREEN_EMERALD, GREENISH, GREEN_PALE, GREEN_YELLOWISH_DEEP, GREEN_LIGHT, GREEN_DEEP,
    YELLOW, YELLOWISH, YELLOWISH_GRAY, YELLOW_ORANGE, YELLOWISH_BROWN,
    PINK, PINK_REDDISH, PINK_VIOLET, PINKISH, PINKISH_LILAC,
    VIOLET, VIOLET_GREYISH, VIOLET_RED,
    GOLD, GOLDEN_YELLOW, GOLDEN_GREEN,
    WHITE, WHITE_TRANSLUCENT,
    PEACH, PEACH_YELLOWISH,
    ORANGE, ORANGE_BROWN,
    OLIVE, OLIVE_GREEN,
    BROWN, CINNAMON,
    IRIDESCENT,
    COLORLESS,
    BLACK,
    GRAY,
    BEIGE,
    INDIGO,
    PURPLE,
    MAUVE,
    LILAC,
    SILVER,
    CREAM
}