package com.epam.streamdp.three.enums;

public enum SemiPreciousGemsNames {
    AQUAMARINE, AMETHYST, AMETRINE, ANDALUSITE, APATITE, BENITOITE, QUARTZ, GARNET, DEMANTOID, DIASPORE, JEREMEJEVITE,
    INDIGOLITE, KYANITE, CORDIERITE, KUNZITE, MOONSTONE, MORGANITE, OPAL, SMOKY_QUARTZ, RHODOLITE, RHODOCHROSITE,
    RUBELLITE, OLIGOCLASE, SPODUMENE, TAAFFEITE, TANZANITE, TOPAZ, TSAVORITE, TOURMALINE, TOURMALINE_PARAIBA, PERIDOT,
    ZIRCON, CITRINE, SPINEL, EUCLASE
}